Tune again

diff --git a/.github/workflows/dockerfile_version_check.yaml b/.github/workflows/dockerfile_version_check.yaml
--- a/.github/workflows/dockerfile_version_check.yaml
+++ b/.github/workflows/dockerfile_version_check.yaml
@@ -55,12 +55,12 @@ jobs:
                 IFS='.' read -r current_major current_minor current_patch <<< "$version_on_main"
 
                 # Check if the image version for this image_name has been incremented in this PR
-                version_this_branch=$(grep -oP "image: .*/$image_name:v\K[0-9]+\.[0-9]+\.[0-9]+" docker-compose.yaml)
+                version_this_branch=$(git diff origin/${{ github.base_ref }}...HEAD -- docker-compose.yaml | grep -oP "image: .*/$image_name:v\K[0-9]+\.[0-9]+\.[0-9]+")
 
-                # if [ -z "$version_this_branch" ]; then
-                #   echo "::error::Dockerfile for $image_name was modified but image version in docker-compose.yaml was not updated."
-                #   exit 1
-                # fi
+                if [ -z "$version_this_branch" ]; then
+                  echo "::error::Dockerfile for $image_name was modified but image version in docker-compose.yaml was not updated."
+                  exit 1
+                fi
 
                 echo "version_this_branch=$new_version"
 
